apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: catalogservice
spec:
  selector:
    matchLabels:
      app: catalogservice
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: catalogservice
        tier: backend
    spec:
      containers:
      - name: catalogservice
        image: arunaja/catalogservice:latest  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PROTOCOL
          value: "jdbc:mysql://"
        - name: SUFIX
          value: "/test?createDatabaseIfNotExist=true&useSSL=false"
        - name: SEPERATOR
          value: ":"
        - name: HOST
          value: $(MYSQL_PORT_3306_TCP_ADDR)$(SEPERATOR)$(MYSQL_SERVICE_PORT)
        - name: spring.datasource.url
          value: $(PROTOCOL)$(HOST)$(SUFIX)    
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: catalogservice
  labels:
    app: catalogservice
    tier: backend
spec:
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    app: catalogservice
    tier: backend