apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bff
spec:
  selector:
    matchLabels:
      app: bff
      tier: middletier
  replicas: 1
  template:
    metadata:
      labels:
        app: bff
        tier: middletier
    spec:
      containers:
      - name: bff
        image: arunaja/k8-bff:2.0  
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PROTOCOL
          value: "http://"
        - name: SUFIX
          value: "/catalog"
        - name: SEPERATOR
          value: ":"
        - name: catalogservice.uri
          value: $(PROTOCOL)$(CATALOGSERVICE_SERVICE_HOST)$(SEPERATOR)$(CATALOGSERVICE_SERVICE_PORT)$(SUFIX)
        - name: server.port
          value: "8080"

        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bff
  labels:
    app: bff
    tier: middletier
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: bff
    tier: middletier